# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HgGit < Formula
  desc ""
  homepage "https://github.com/yapaluc/hg-git"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yapaluc/hg-git/releases/download/v0.1.2/hg-git_Darwin_x86_64.tar.gz"
      sha256 "90d56b65b15637ecdfbac452d51f1c4ba332041a0a692524ea08b9f402e16faa"

      def install
        bin.install "hg-git"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yapaluc/hg-git/releases/download/v0.1.2/hg-git_Darwin_arm64.tar.gz"
      sha256 "c47abc84f6c3cedba280b406f2b2ed34cd769d00a0a295ec4a068119008e2197"

      def install
        bin.install "hg-git"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yapaluc/hg-git/releases/download/v0.1.2/hg-git_Linux_x86_64.tar.gz"
      sha256 "2e74681dee66a8c98ba94ef14a1304cb62d1a8dc7d8f021a22a8e0a84a1da87a"

      def install
        bin.install "hg-git"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yapaluc/hg-git/releases/download/v0.1.2/hg-git_Linux_arm64.tar.gz"
      sha256 "3a8ac13599c033fd3793b49568adf242f3a1b79ca4ce6f98a8dbf39cacc00ffd"

      def install
        bin.install "hg-git"
      end
    end
  end
end
