# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HgGit < Formula
  desc ""
  homepage "https://github.com/yapaluc/hg-git"
  version "0.1.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yapaluc/hg-git/releases/download/v0.1.18/hg-git_Darwin_x86_64.tar.gz"
      sha256 "f89001e53e4d7a07b7f0f63a8cc9bd9c25eb9ba3ae0fcf0acf0cb180460e8822"

      def install
        bin.install "hg-git"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yapaluc/hg-git/releases/download/v0.1.18/hg-git_Darwin_arm64.tar.gz"
      sha256 "836cc447e42fed1ff573f4ad286991abab441c3c2f9f382b9dce80d02fb4ad80"

      def install
        bin.install "hg-git"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yapaluc/hg-git/releases/download/v0.1.18/hg-git_Linux_arm64.tar.gz"
      sha256 "c6b1713644c0d51644a9294bf8a230826e9ea80798007f8e05b3fc2f7d7bffd6"

      def install
        bin.install "hg-git"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yapaluc/hg-git/releases/download/v0.1.18/hg-git_Linux_x86_64.tar.gz"
      sha256 "e58da7614dfe6880d6d1ce794aa2a3806a9431a2ad35a30a07ce46030b3586f3"

      def install
        bin.install "hg-git"
      end
    end
  end
end
